services:
  frontend:
    build: ./frontend
    ports:
      - 3003:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_IMAGE_URL=http://localhost:8000
      - NEXT_PUBLIC_API_TOKEN=${NEXT_PUBLIC_API_TOKEN}
      - API_URL=${API_URL}
    env_file:
      - ./frontend/.env
  # nginx:
  #   image: nginx:1.21.3
  #   depends_on:
  #     - frontend
  #   restart: always
  #   ports:
  #     - ${GATEWAY_PORT:-8000}:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./logs:/var/log/nginx-dev

volumes:
  portfolio-data:
  portfolio-data-test: